FROM golang:1.25-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /greeter-service ./cmd/server

FROM alpine:3.20
COPY --from=build /greeter-service /greeter-service
EXPOSE 50052
ENTRYPOINT ["/greeter-service"]
